### ISSUE TITLE
.NET MAUI 9 SR5: CSS support for Border

### ISSUE THREAD

**Issue by davidbritch** [dotnet/docs-maui#2835]
Basic support for CSS properties that work on `Border`:

```css
.myNicePurpleBorder
{
   border-color: #512BD4; /* Also supports linear-gradient, radial-gradient, named colors etc. */
   border-radius: 10; /* Always maps to RoundRectangle [Radius] internally */
   border-width: 4;
}
```

More info: https://github.com/dotnet/maui/pull/27529

---
[Associated WorkItem - 406716](https://dev.azure.com/msft-skilling/Content/_workitems/edit/406716)
